
name: Build Test
on: [push]

jobs:
  kineticbuild:
    runs-on: ubuntu-latest
    container: ros:kinetic-robot
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: release_build_test
      working-directory: 
      run: |
        apt update
        apt install -y python3-wstool
        mkdir -p $HOME/catkin_ws/src;
        cd $HOME/catkin_ws
        catkin init
        catkin config --extend "/opt/ros/kinetic"
        catkin config --merge-devel
        cd $HOME/catkin_ws/src
        ln -s $GITHUB_WORKSPACE
        cd $HOME/catkin_ws
        rosdep update
        rosdep install --from-paths doosan-robot --ignore-src --rosdistro kinetic -r -y
        catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release -DCATKIN_ENABLE_TESTING=False
        catkin build -j$(nproc) -l$(nproc)